export const LOCAL_STORAGE_PASSWORD_KEY_NAME = 'password'
export const LOCAL_STORAGE_USERNAME_KEY_NAME = 'username'
export const LOCAL_STORAGE_SHOPPING_LISTS_KEY_NAME = 'shopping-lists'

export const getAllShoppingListsMainQueryKey = 'get-all-shopping-lists'
export const getUsernameQueryKey = 'get-username'
export const getShoppingListMainQueryKey = 'get-shopping-list'
export const getProductsMainQueryKey = 'get-products'
export const getProductByIdMainQueryKey = 'get-product-by-id'
export const healthMainQueryKey = 'health'
export const getLatestChangelogEntriesMainQueryKey = 'changelog-latest-entries'
export const getAllUnitsQueryKey = 'all-units'